'''
===================
Lists are mutable
Strings are immutable

Print the method names of Lists: print(dir([]))
==================
my_list=[]
my_list=[2,8,3,"python",7.2,]
bool(empty_list)==>False
bool(non_empty_list)==>True

my_list=[2,8,3,"python",7.2,]
print(my_list,type(my_list))
print(my_list[0])
print(my_list[3])
print(my_list[-1])
print(my_list[3][1])
print(my_list)
print(my_list[:])
print(my_list[0:])
my_list[0]=25
print(my_list)
'''
'''
my_list=[3,2,7,5,9,2,1,2]
print(my_list)
print(my_list.index(9))
#print(my_list.index(6))
print(my_list.count(2))
print(my_list.count(6))
my_list.clear()
print(my_list)
'''
'''
my_list=[3,2,7,5,9,2,1,2]
my_new_list=my_list
my_one_list=my_list.copy()
print(id(my_list),id(my_new_list))
print(id(my_one_list))
'''
my_list=[3,2,7,5,9,2,1,2]
print(my_list)
my_list.append(40)
print(my_list)
my_list.insert(1,56)
print(my_list)
my_new_list=[55,66]
my_list.append(50)
print(my_list)
my_list.append(my_new_list)
print(my_list)
my_list.extend(my_new_list)
print(my_list)
my_list.remove([55,66])
print(my_list)
my_list.pop()
print(my_list)
my_list.pop(0)
print(my_list)
my_list.reverse()
print(my_list)
my_list.sort()
print(my_list)
my_list.sort(reverse=True)
print(my_list)
